version: '3'
services:
    client:
      build: ./client/.
      container_name: client
      volumes:
       - ./client/squid:/var/spool/squid
      networks:
        network1:
            ipv4_address: 10.0.4.100
            aliases:
              - client
        network2:
    p1:
      build: ./m1/.
      volumes:
       - ./m1/conf:/etc/squid
       - ./m1/logs:/var/log/squid/
       - ./m1/squid:/var/spool/squid
      networks:
        network1:
            ipv4_address: 10.0.4.101
            aliases:
              - p1
        network2:
      container_name: p1

    p2:
      build: ./m2/.
      volumes:
        - ./m2/conf:/etc/squid
        - ./m2/logs:/var/log/squid/
        - ./m2/squid:/var/spool/squid
      networks:
        network1:
            ipv4_address: 10.0.4.102
            aliases:
              - p2
        network2:
      container_name: p2

    p3:
      build: ./m3/.
      volumes:
       - ./m3/conf:/etc/squid
       - ./m3/logs:/var/log/squid/
       - ./m3/squid:/var/spool/squid
      networks:
        network1:
            ipv4_address: 10.0.4.103
            aliases:
              - p3
      container_name: p3

networks:
  network1:
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 10.0.4.0/24
  network2:
