version: '3'
services:
    client:
      build: ./client/.
      # links:
      #   - "p1:p1"
      #   - "p2:p2"
      #   - "p3:p3"
      container_name: client
      volumes:
       - ./client/squid:/var/spool/squid
      networks:
        network1:
            aliases:
              - client
    p1:
      build: ./m1/.
      volumes:
       - ./m1/conf:/etc/squid
       - ./m1/logs:/var/log/squid/
       - ./m1/squid:/var/spool/squid
      networks:
        network1:
            aliases:
              - p1
        network2:
        # network1:
               # ipv4_address: 10.0.1.3
      # links:
      #   - "p2:p2"
      #   - "p3:p3"
      container_name: p1

    p2:
      build: ./m2/.
      volumes:
        - ./m2/conf:/etc/squid
        - ./m2/logs:/var/log/squid/
        - ./m2/squid:/var/spool/squid
      networks:
        network1:
            aliases:
              - p2
        network2:
      # links:
      #   - "p1:p1"
      #   - "p3:p3"
      container_name: p2

    p3:
      build: ./m3/.
      volumes:
       - ./m3/conf:/etc/squid
       - ./m3/logs:/var/log/squid/
       - ./m3/squid:/var/spool/squid
      networks:
        network1:
            aliases:
              - p3
      # links:
      #   - "p1:p1"
      #   - "p2:p2"
      container_name: p3

# volumes:
#   logs_m1:
#     driver_opts:
#       device: m1/logs
#       o: ro

networks:
  network1:
    driver: bridge
    internal: true
  network2:
  # squid_net:
  #     driver: bridge
  #     ipam:
  #       config:
  #         - subnet: 10.0.1.0/24
